// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy889J8ygvH7VSrYBQE42cL9IwImMhO4U',
    appId: '1:849533245373:web:275212eec3d49201fba4d4',
    messagingSenderId: '849533245373',
    projectId: 'coralz-ce067',
    authDomain: 'coralz-ce067.firebaseapp.com',
    storageBucket: 'coralz-ce067.appspot.com',
    measurementId: 'G-1LS3HKSVF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCae2K-jS3unXmqQsfvBlqapXEmuqJOXaA',
    appId: '1:849533245373:android:2872fc4c1c1b0426fba4d4',
    messagingSenderId: '849533245373',
    projectId: 'coralz-ce067',
    storageBucket: 'coralz-ce067.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMDLs7HnrDVsCB6JDjsTg-iwcUGWp7bec',
    appId: '1:849533245373:ios:0e219f98faa3d2fafba4d4',
    messagingSenderId: '849533245373',
    projectId: 'coralz-ce067',
    storageBucket: 'coralz-ce067.appspot.com',
    iosClientId: '849533245373-0ir8djebf4dbmi9a1dirf9831qsjhunn.apps.googleusercontent.com',
    iosBundleId: 'com.example.coralz',
  );
}
